### ISSUE TITLE
Unable to execute go chaos-executer 

### ISSUE THREAD

**Issue by amitbhatt818** [litmuschaos/chaos-executor#20]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:
error:
```
time="2020-01-02T10:17:58Z" level=info msg="Experiments List:  [pod-network-latency]   Engine Name:  engine-nginx   appLabels :  app=nginx   appNamespace:  default   appKind:     Service Account Name:  amit"
time="2020-01-02T10:17:58Z" level=info msg="Printing experiment.Name: pod-network-latency, experiment.Namespace : default"
time="2020-01-02T10:17:58Z" level=info msg="Going with the experiment Name: pod-network-latency"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xfbdc75]

goroutine 1 [running]:
github.com/litmuschaos/chaos-executor/vendor/github.com/litmuschaos/chaos-operator/pkg/client/clientset/versioned.(*Clientset).LitmuschaosV1alpha1(...)
	/home/circleci/go/src/github.com/litmuschaos/chaos-executor/vendor/github.com/litmuschaos/chaos-operator/pkg/client/clientset/versioned/clientset.go:42
github.com/litmuschaos/chaos-executor/pkg/utils.(*ExperimentDetails).CheckExistence(0xc42030dd90, 0x0, 0x0, 0xc4202970c0)
	/home/circleci/go/src/github.com/litmuschaos/chaos-executor/pkg/utils/experimentHelpers.go:21 +0x45
main.main()
	/home/circleci/go/src/github.com/litmuschaos/chaos-executor/bin/exec.go:77 +0x677

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by amitbhatt818** [comment]
#21
